import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Rubik_Moonrocks } from 'next/font/google'
import { Roboto } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Estimate Generator',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

const rubik = Rubik_Moonrocks({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className='flex bg-blue-50 min-h-screen'>
        {children}
      </body>
    </html>
  )
}