import Header from "@/components/misc/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import React from "react";

export const metadata: Metadata = {
  title: "Estimate Generator",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="flex flex-col bg-blue-50 min-h-screen">
        <Header />
        {children}
      </body>
    </html>
  );
}
