import '../globals.css'
import SideMenu from "../components/SideMenu"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex min-h-screen'>
        <SideMenu />
        {children}
      </body>
    </html>
  )
}
