export const states = [
  { label: "AL", state: "Alabama", id: 1 },
  { label: "AK", state: "Alaska", id: 2 },
  { label: "AZ", state: "Arizona", id: 3 },
  { label: "AR", state: "Arkansas", id: 4 },
  { label: "CA", state: "California", id: 5 },
  { label: "CO", state: "Colorado", id: 6 },
  { label: "CT", state: "Connecticut", id: 7 },
  { label: "DE", state: "Delaware", id: 8 },
  { label: "FL", state: "Florida", id: 9 },
  { label: "GA", state: "Georgia", id: 10 },
  { label: "HI", state: "Hawaii", id: 11 },
  { label: "ID", state: "Idaho", id: 12 },
  { label: "IL", state: "Illinois", id: 13 },
  { label: "IN", state: "Indiana", id: 14 },
  { label: "IA", state: "Iowa", id: 15 },
  { label: "KS", state: "Kansas", id: 16 },
  { label: "KY", state: "Kentucky", id: 17 },
  { label: "LA", state: "Louisiana", id: 18 },
  { label: "ME", state: "Maine", id: 19 },
  { label: "MD", state: "Maryland", id: 20 },
  { label: "MA", state: "Massachusetts", id: 21 },
  { label: "MI", state: "Michigan", id: 22 },
  { label: "MN", state: "Minnesota", id: 23 },
  { label: "MS", state: "Mississippi", id: 24 },
  { label: "MO", state: "Missouri", id: 25 },
  { label: "MT", state: "Montana", id: 26 },
  { label: "NE", state: "Nebraska", id: 27 },
  { label: "NV", state: "Nevada", id: 28 },
  { label: "NH", state: "New Hampshire", id: 29 },
  { label: "NJ", state: "New Jersey", id: 30 },
  { label: "NM", state: "New Mexico", id: 31 },
  { label: "NY", state: "New York", id: 32 },
  { label: "NC", state: "North Carolina", id: 33 },
  { label: "ND", state: "North Dakota", id: 34 },
  { label: "OH", state: "Ohio", id: 35 },
  { label: "OK", state: "Oklahoma", id: 36 },
  { label: "OR", state: "Oregon", id: 37 },
  { label: "PA", state: "Pennsylvania", id: 38 },
  { label: "RI", state: "Rhode Island", id: 39 },
  { label: "SC", state: "South Carolina", id: 40 },
  { label: "SD", state: "South Dakota", id: 41 },
  { label: "TN", state: "Tennessee", id: 42 },
  { label: "TX", state: "Texas", id: 43 },
  { label: "UT", state: "Utah", id: 44 },
  { label: "VT", state: "Vermont", id: 45 },
  { label: "VA", state: "Virginia", id: 46 },
  { label: "WA", state: "Washington", id: 47 },
  { label: "WV", state: "West Virginia", id: 48 },
  { label: "WI", state: "Wisconsin", id: 49 },
  { label: "WY", state: "Wyoming", id: 50 },
];
